name: 基金日报定时推送
on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'  # 北京时间19:00
jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 安装依赖
        run: pip install -r requirements.txt
      - name: 运行推送脚本
        run: python publish_to_wechat.py
